version: '3'
services:
    tomcat:
        image: my-tomcat
        ports:
            - 1234:8080
        # deploy:
        #   replicas: 5
        #   resources:
        #     limits:
        #       cpus: "0.1"
        #       memory: 50M
        #   restart_policy:
        #     condition: on-failure
        networks:
            - app-network
networks:
    app-network:
